# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lSFQnMZG63v50NHLy57C6GAc404iy2b
"""

import torch
import torch.optim as optim
import torchvision
from torch.utils.data import DataLoader
from model import CNN

# Define data loaders
num_batch = 64
transform = torchvision.transforms.Compose([
    torchvision.transforms.ToTensor()
])
train_data = torchvision.datasets.MNIST('mnist_data', train=True, download=True, transform=transform)
test_data = torchvision.datasets.MNIST('mnist_data', train=False, download=True, transform=transform)
val_data = torchvision.datasets.MNIST('mnist_data', train=True, download=True, transform=transform)
train_loader = DataLoader(train_data, batch_size=num_batch)
val_loader = DataLoader(val_data, batch_size=num_batch)
test_loader = DataLoader(test_data, batch_size=num_batch)

# Create model, optimizer, and loss function
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = CNN().to(device)
optimizer = optim.Adam(model.parameters(), lr=0.001)
loss_fn = torch.nn.CrossEntropyLoss()

# Training loop
def train(epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = loss_fn(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % 20 == 0:
            print(f'Train Epoch: {epoch} [{batch_idx * len(data)}/{len(train_loader.dataset)} ({100. * batch_idx / len(train_loader):.0f}%)]\t{loss.item():.6f}')

# Run training loop
for epoch in range(1, 11):
    train(epoch)